dev:
  deploy:
    parameters:
      stack_name: stream-post-processor
      s3_prefix: stream-post-processor
      region: us-east-1
      capabilities: CAPABILITY_IAM
      image_repositories: []
      parameter_overrides:
        - MaxTracksPerEpisode=50
        - TrackSelectionLogLevel=INFO
      tags:
        - project=stream-post-processor
  global:
    parameters:
      region: us-east-1
version: 0.1
