name: Deploy Sandbox
run-name: Deploy ${{ github.actor }} Sandbox

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  # pre-deploy:
  #   name: Pre-deploy validations
  #   uses: ./.github/workflows/shared-pre-deploy-validations.yaml

  prepare-deployment:
    name: Prepare Deployment
    runs-on: ubuntu-latest
    outputs:
      env_descriptor: ${{ steps.prepare-parameters.outputs.env_descriptor }}
      env_hash: ${{ steps.prepare-parameters.outputs.env_hash }}
    steps:
      - name: Prepare parameters
        id: prepare-parameters
        run: |
          ENV_DESCRIPTOR="env-${{ github.actor }}"
          ENV_HASH=$(echo -n "$ENV_DESCRIPTOR" | sha1sum | cut -c1-6)


          echo "ENV_DESCRIPTOR=$ENV_DESCRIPTOR" >> $GITHUB_ENV
          echo "ENV_HASH=$ENV_HASH" >> $GITHUB_ENV
          echo "# RUN METADATA" >> $GITHUB_STEP_SUMMARY
          echo "* Environment Descriptor - $ENV_DESCRIPTOR" >> $GITHUB_STEP_SUMMARY
          echo "* Environment Hash - $ENV_HASH" >> $GITHUB_STEP_SUMMARY

          echo "env_descriptor=$ENV_DESCRIPTOR" >> $GITHUB_OUTPUT
          echo "env_hash=$ENV_HASH" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy
    needs: [prepare-deployment]
    uses: ./.github/workflows/shared-deploy.yaml
    with:
      ENV: dev
      STACK_NAME: stream-post-processor-${{ needs.prepare-deployment.outputs.env_descriptor }}
      ENV_HASH: ${{ needs.prepare-deployment.outputs.env_hash }}
    secrets: inherit