name: Deploy

on:
  workflow_call:
    inputs:
      ENV:
        type: string
        required: true
      STACK_NAME:
        type: string
        required: true
      ENV_HASH:
        type: string
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.PIPELINE_EXECUTION_ROLE }}

      # - name: Validate template
      #   run: |
      #     sam validate -t template.yaml

      - name: Replace Variables in samconfig
        env:
          STACK_NAME: ${{ inputs.STACK_NAME }}
          ENV_HASH: ${{ inputs.ENV_HASH }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        run: |
          envsubst < samconfig.yaml.template > samconfig.yaml

          echo "Generated samconfig.yaml:"
          cat samconfig.yaml

      - name: Deploy stack
        run: |
          npm install -g esbuild

          npm ci

          sam build \
            --template-file template.yaml

          sam deploy \
            --config-file samconfig.yaml \
            --config-env ${{ inputs.ENV }} \
            --s3-bucket "${{ secrets.ARTIFACTS_BUCKET_NAME }}" \
            --role-arn "${{ secrets.CLOUDFORMATION_EXECUTION_ROLE }}" \
            --no-fail-on-empty-changeset
